name: tests
on:
  push:
    paths: ['test/**','src/**']
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 'latest'

      - name: Run Unit Tests
        run: clojure -M:test "$@" unit

      - name: Test Dispatch
        run: clojure -M:test "$@" dispatch

      - name: Test Resolver
        run: clojure -M:test "$@" resolver

      - name: Run end-to-end tests
        run: clojure -M:test "$@" e2e
